# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d954c02330fd8ea9c2fdf41dfa252a91151c550db4da4a16d54c4c2895ae8d2a63e9eccfe7b64addae862d5632175653ab3245abb1daf759443dfe8e49644d1

test:
  secret_key_base: 931fab839937de2fddaed4c2cfa753f7da2e84bbf26faeb89facc8b5a96e260a5254f6acd5a18da6fc020ccc0c83b2b292cc2ca548930ad739e98a18de5474d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
